name: GhostMute
main: com.djrapitops.ghostmute.GhostMute
version: 1.1.1

commands:
  ghostreload:
    usage: /ghostreload
    description: Reloads config
  gmute:
    usage: /gmute <player>
    description: Mutes/unmutes the player.
  gmutelist:
    usage: /gmutelist
    description: Lists muted players.
permissions:
  GhostMute.mute:
    description: Mute/unmute players
    default: op
  GhostMute.bypass:
    description: Bypasses fake message being shown
    default: false
  GhostMute.reload:
    description: Reloads config
    default: op